// GENERATED — do not hand-edit. Regenerate with scripts/gen-proto-real-data.mjs.
//
// Real VSCN members for the /proto/community prototype. Snapshot of the
// `publicProfiles` collection taken 2026-08-21; `active === false` accounts are
// excluded. Images are the curated portfolio picks from Design/member-curation,
// downscaled to 1200px WebP into public/proto/img/real/ (see the same script).
//
// 21 members, 16 of them with images. The 5 without are real
// profiles that have no artwork anywhere to curate from — they are kept in the
// data on purpose and need the typographic card variant to render.
import type { ProtoImage, ProtoMember, ProtoMemberDetail } from "./proto-data.ts";

export interface ProtoRealMember extends ProtoMember, ProtoMemberDetail {
  /** Every tag on the profile. The card rail only has room for a few. */
  tags: string[];
  images: ProtoImage[];
}

export const PROTO_REAL_MEMBERS: ProtoRealMember[] = [
  {
    id: "anna-buergisser",
    name: "Anna Bürgisser",
    role: "Science Illustrator",
    description: "",
    bio: "",
    tags: ["Scientific Illustration","Data Visualization","Education","Environmental Science","Medicine","Infographic","Microbiology"],
    openTo: [],
    portfolio: "",
    socialMedia: "",
    hasPhoto: true,
    images: [],
  },
  {
    id: "daniel-roettele",
    name: "Daniel Röttele",
    role: "Infografiker, Visueller Journalist, Illustrator, Typograf",
    description: "Ich visualisiere Wissen/Zusammenhänge und unterrichte dazu auch.",
    bio: "Ich visualisiere Wissen/Zusammenhänge und unterrichte dazu auch. Viele Jahre Berufserfahrung. Eigene Firma ab 2013 mit Arbeiten für Kunden aus den Bereichen Medien, Unternehmen, Bildungsinstitute sowie für NGOs. Seit 2014 Gastdozent und Mentor an verschiedenen Bildungseinrichtungen.",
    tags: ["Journalism","Science Communication","Data Visualization","Animation","Scientific Illustration","Illustration","Education"],
    openTo: [],
    portfolio: "www.danielroettele.ch",
    socialMedia: "www.instagram.com/daniel_roettele/",
    hasPhoto: true,
    images: [
      { src: "/proto/img/real/daniel-roettele/01-stromnetz-spannung-pur.webp", width: 1000, height: 707 },
      { src: "/proto/img/real/daniel-roettele/02-eawag-abwasser.webp", width: 1000, height: 591 },
      { src: "/proto/img/real/daniel-roettele/03-nzz-darwin-evolution.webp", width: 1000, height: 714 },
    ],
  },
  {
    id: "esther-schoenenberger",
    name: "Esther Schönenberger",
    role: "Bereichsleiterin Grabungstechnik, Archäologie und Denkmalpflege",
    description: "",
    bio: "",
    tags: ["3D","Scientific Illustration","Archaeology"],
    openTo: [],
    portfolio: "",
    socialMedia: "",
    hasPhoto: false,
    images: [],
  },
  {
    id: "gabriela-g",
    name: "Gabriela G.",
    role: "Scientific Illustrator",
    description: "Hi, I love mixing analogue techniques and hand-drawing with 3D models to render visions for…",
    bio: "Hi, I love mixing analogue techniques and hand-drawing with 3D models to render visions for pop-science communication. Now, making my first steps as a freelancer.",
    tags: [],
    openTo: [],
    portfolio: "www.scenecraftz.com",
    socialMedia: "",
    hasPhoto: true,
    images: [],
  },
  {
    id: "gregor-forster",
    name: "Gregor Forster",
    role: "Illustrator",
    description: "",
    bio: "",
    tags: ["Illustration","Zoology","Editorial Illustration","Natural Sciences","Education"],
    openTo: ["offering"],
    portfolio: "gregorforster.com",
    socialMedia: "https://.instagram.com/gregor.forster/",
    hasPhoto: false,
    images: [
      { src: "/proto/img/real/gregor-forster/01-abc-under-the-sea.webp", width: 1200, height: 1000 },
      { src: "/proto/img/real/gregor-forster/02-haie-anatomie.webp", width: 1200, height: 1000 },
      { src: "/proto/img/real/gregor-forster/03-haie-merkmale.webp", width: 1200, height: 1000 },
    ],
  },
  {
    id: "ikonaut",
    name: "ikonaut",
    role: "Scientific Visualization Studio",
    description: "ikonaut are Thomas Erdin, David Schürch, and Jonas Christen.",
    bio: "ikonaut are Thomas Erdin, David Schürch, and Jonas Christen. As scientific illustrators, we are specialized in translating complex content into a clear visual language.",
    tags: ["3D","Scientific Illustration","Archaeology","Natural Sciences","Environmental Science","Climate Science","Infographic"],
    openTo: ["offering","networking","coolaborate"],
    portfolio: "www.ikonaut.ch",
    socialMedia: "https://www.linkedin.com/company/ikonaut/",
    hasPhoto: true,
    images: [
      { src: "/proto/img/real/ikonaut/01-esa-fernerkundung.webp", width: 1200, height: 675 },
      { src: "/proto/img/real/ikonaut/02-3d-rekonstruktion-frauenfeld.webp", width: 1200, height: 675 },
      { src: "/proto/img/real/ikonaut/03-slf-lawinen.webp", width: 1200, height: 1200 },
    ],
  },
  {
    id: "janina-hess",
    name: "Janina Hess",
    role: "Designer & Illustrator",
    description: "",
    bio: "",
    tags: ["Illustration","Animation","Scientific Illustration","Graphic Design","Branding","Editorial Illustration"],
    openTo: [],
    portfolio: "www.janinahess.ch",
    socialMedia: "https://www.linkedin.com/in/janina-hess/",
    hasPhoto: false,
    images: [
      { src: "/proto/img/real/janina-hess/01-nachrichten-tagebuch.webp", width: 600, height: 800 },
      { src: "/proto/img/real/janina-hess/02-srf-we-myself-why.webp", width: 600, height: 800 },
      { src: "/proto/img/real/janina-hess/03-nikin-together-for-nature.webp", width: 600, height: 800 },
    ],
  },
  {
    id: "jasmin",
    name: "Jasmin",
    role: "Science Illustrator",
    description: "Exploring the entanglement of the world.",
    bio: "Exploring the entanglement of the world. Analog drawing. Background in environmental science. I'm a certified scientific Illustrator. I help you to create a vision for your scientific work with the means of art. Newsletter soon",
    tags: ["Data Visualization","Design Research","Illustration","Writing","Botany","Ecology","Anthropology"],
    openTo: [],
    portfolio: "",
    socialMedia: "compostdiv4",
    hasPhoto: true,
    images: [
      { src: "/proto/img/real/jasmin/01-zwischen-kies-und-maeandern.webp", width: 1080, height: 809 },
      { src: "/proto/img/real/jasmin/02-birdlife-spatz.webp", width: 1200, height: 1200 },
      { src: "/proto/img/real/jasmin/03-rosarot-hitzig.webp", width: 960, height: 1200 },
    ],
  },
  {
    id: "jasmin-peter",
    name: "Jasmin Peter",
    role: "Scientific Visualization",
    description: "I finished my Bachelor’s degree in Knowledge Visualization at ZHdK in 2026 with a Minor in…",
    bio: "I finished my Bachelor’s degree in Knowledge Visualization at ZHdK in 2026 with a Minor in Publishing and Unternehmerisches Denken und Handeln.",
    tags: [],
    openTo: [],
    portfolio: "jasminpeter.ch",
    socialMedia: "https://www.instagram.com/jasminpeterart?igsh=Mnk0cmJtcGw4MWsz&utm_source=qr",
    hasPhoto: true,
    images: [
      { src: "/proto/img/real/jasmin-peter/01-nervenzelle.webp", width: 1200, height: 842 },
      { src: "/proto/img/real/jasmin-peter/02-genmutation-denaturierung.webp", width: 1200, height: 675 },
      { src: "/proto/img/real/jasmin-peter/03-pferdedarm-anatomie.webp", width: 1200, height: 851 },
    ],
  },
  {
    id: "joshua-binswanger",
    name: "Joshua Binswanger",
    role: "Scientific Illustrator",
    description: "Scientific illustrator specializing in 3D and web technologies.",
    bio: "Scientific illustrator specializing in 3D and web technologies. I combine design and aesthetics to make complex knowledge intuitively accessible. Currently contributing to a medical learning app at Augmedi AG.",
    tags: ["3D","Natural Sciences","Web Development","Scientific Illustration","Medicine","Environmental Science"],
    openTo: ["offering","networking","coolaborate","events"],
    portfolio: "rhizome.ch",
    socialMedia: "https://www.instagram.com/rhizome.ch/",
    hasPhoto: true,
    images: [
      { src: "/proto/img/real/joshua-binswanger/01-xylopedia-ct-oak.webp", width: 1067, height: 1200 },
      { src: "/proto/img/real/joshua-binswanger/02-borkenkaefer.webp", width: 1000, height: 1200 },
      { src: "/proto/img/real/joshua-binswanger/03-phenological-shift.webp", width: 1067, height: 1200 },
    ],
  },
  {
    id: "karin-s",
    name: "Karin S.",
    role: "Designer and Lecturer Head of  Bachelor Major Knowledge Visualization Zurich University of the Arts",
    description: "Passionate about Visual Literacy in Design, Science and Society.",
    bio: "Passionate about Visual Literacy in Design, Science and Society.",
    tags: [],
    openTo: ["networking"],
    portfolio: "kvis.zhdk.ch/personen/team/karin-seiler/",
    socialMedia: "@karin_seiler, https://www.linkedin.com/in/karin-seiler-24107497/",
    hasPhoto: true,
    images: [],
  },
  {
    id: "liliane-gschwend",
    name: "Liliane Gschwend",
    role: "Scientific Illustrator / Archaeological excavator",
    description: "",
    bio: "",
    tags: ["Illustration","Scientific Illustration","Data Visualization","Archaeology","Anthropology","Botany","Zoology"],
    openTo: ["networking","offering","events","coolaborate"],
    portfolio: "",
    socialMedia: "https://www.instagram.com/lilis.illustrations/#",
    hasPhoto: true,
    images: [
      { src: "/proto/img/real/liliane-gschwend/01-catocala-fulminea.webp", width: 1200, height: 1200 },
      { src: "/proto/img/real/liliane-gschwend/02-naturstudie-wald.webp", width: 1200, height: 1200 },
      { src: "/proto/img/real/liliane-gschwend/03-pilze.webp", width: 960, height: 1200 },
    ],
  },
  {
    id: "lisa-cuthbertson",
    name: "Lisa Cuthbertson",
    role: "Medical/Scientific Illustrator",
    description: "",
    bio: "",
    tags: [],
    openTo: [],
    portfolio: "",
    socialMedia: "https://www.instagram.com/lisacuth.illustration?igsh=d2kyeTlsdWE1ZzV6",
    hasPhoto: false,
    images: [
      { src: "/proto/img/real/lisa-cuthbertson/01-hand-nerven.webp", width: 970, height: 1200 },
      { src: "/proto/img/real/lisa-cuthbertson/02-divertikulitis.webp", width: 1080, height: 765 },
      { src: "/proto/img/real/lisa-cuthbertson/03-femurkopf-studie.webp", width: 1080, height: 764 },
    ],
  },
  {
    id: "lisa-sophia-sommer",
    name: "Lisa Sophia Sommer",
    role: "Medical and Scientific Illustrator, 3D-Designer",
    description: "",
    bio: "",
    tags: [],
    openTo: [],
    portfolio: "",
    socialMedia: "https://www.instagram.com/lisa.som.illustrations/",
    hasPhoto: false,
    images: [
      { src: "/proto/img/real/lisa-sophia-sommer/01-krokodilschaedel-studie.webp", width: 1200, height: 933 },
      { src: "/proto/img/real/lisa-sophia-sommer/02-kopf-querschnitt.webp", width: 1009, height: 1200 },
      { src: "/proto/img/real/lisa-sophia-sommer/03-chrysochus-cobaltinus.webp", width: 1200, height: 1200 },
    ],
  },
  {
    id: "michael-stuenzi",
    name: "Michael Stünzi",
    role: "Wissenschaftlicher Illustrator, Infografiker und Dozent",
    description: "Ich konzipiere wissenschaftliche Illustrationen, informative Visualisierungen, Infografiken und…",
    bio: "Ich konzipiere wissenschaftliche Illustrationen, informative Visualisierungen, Infografiken und animierte Erklärfilme, je nach Projekt für gedruckte und digitale Anwendungen sowie für räumliche Inszenierungen. Als Dozent unterrichte ich an verschiedenen Instituten und Schulen.",
    tags: ["Scientific Illustration","Animation","Education","Exhibition Design","Illustration","Motion Graphics","Infographic"],
    openTo: [],
    portfolio: "www.mstuenzi.ch",
    socialMedia: "",
    hasPhoto: true,
    images: [
      { src: "/proto/img/real/michael-stuenzi/01-spechtarten-vogelwarte.webp", width: 1200, height: 835 },
      { src: "/proto/img/real/michael-stuenzi/02-mikroplastik-oceancare.webp", width: 849, height: 1200 },
      { src: "/proto/img/real/michael-stuenzi/03-pankreas-medizinisch.webp", width: 1200, height: 848 },
    ],
  },
  {
    id: "oliver-bruderer",
    name: "Oliver Bruderer",
    role: "Scientific Illustrator & Lecturer at UZH",
    description: "Scientific illustrator & lecturer at the department of Archaeology at the University of Zurich…",
    bio: "Scientific illustrator & lecturer at the department of Archaeology at the University of Zurich (UZH). – Teaching assistant at the Master Knowledge Visualization at the Zurich University of the Arts (ZHdK).",
    tags: ["3D","Design Research","Scientific Illustration","Archaeology"],
    openTo: ["networking","events","Conferences","Group Exhibitions","Design Research"],
    portfolio: "archaeovisual.ch",
    socialMedia: "",
    hasPhoto: true,
    images: [
      { src: "/proto/img/real/oliver-bruderer/01-weinkelter-tell-el-burak.webp", width: 1200, height: 849 },
      { src: "/proto/img/real/oliver-bruderer/02-kalapodi-pferdekopf-prozess.webp", width: 1200, height: 450 },
      { src: "/proto/img/real/oliver-bruderer/03-amarynthos-oststoa-cad.webp", width: 1200, height: 750 },
    ],
  },
  {
    id: "quaint",
    name: "Quaint",
    role: "Visualization Studio",
    description: "Look closer, understand deeper.",
    bio: "Look closer, understand deeper. Your studio for clear, charming, and scientifically accurate visual communication. Our team: Alessandro Holler, Sandro Lochau, Leana Wirth, Rachel Spinnler",
    tags: ["3D","Animation","Exhibition Design","Scientific Illustration","Branding","Life Sciences","Medicine"],
    openTo: ["offering","networking"],
    portfolio: "quaint.ch",
    socialMedia: "instagram.com/quaintvisualization",
    hasPhoto: true,
    images: [
      { src: "/proto/img/real/quaint/01-metatarsophalangeal-joint.webp", width: 1200, height: 1200 },
      { src: "/proto/img/real/quaint/02-bio-oss-collagen.webp", width: 1200, height: 1200 },
      { src: "/proto/img/real/quaint/03-geo-engineering.webp", width: 1013, height: 1013 },
    ],
  },
  {
    id: "selina-bachmann",
    name: "Selina Bachmann",
    role: "Wissenschaftliche Illustratorin",
    description: "",
    bio: "",
    tags: [],
    openTo: [],
    portfolio: "",
    socialMedia: "https://www.instagram.com/selinabachmann",
    hasPhoto: false,
    images: [
      { src: "/proto/img/real/selina-bachmann/01-snowdrop-galanthus.webp", width: 961, height: 1200 },
      { src: "/proto/img/real/selina-bachmann/02-das-haushuhn.webp", width: 960, height: 1200 },
      { src: "/proto/img/real/selina-bachmann/03-rhinanthus.webp", width: 933, height: 1200 },
    ],
  },
  {
    id: "stefan-scherrer",
    name: "Stefan Scherrer",
    role: "Scientific Illustrator / Designer",
    description: "",
    bio: "",
    tags: ["Medicine","Scientific Illustration","3D","Anthropology","Paleontology"],
    openTo: ["events","coolaborate","offering","seeking","networking"],
    portfolio: "stefan-scherrer.ch",
    socialMedia: "https://www.instagram.com/scivisual/",
    hasPhoto: true,
    images: [
      { src: "/proto/img/real/stefan-scherrer/01-eth-bakterien-konjugation.webp", width: 1200, height: 675 },
      { src: "/proto/img/real/stefan-scherrer/02-nektarium-museum.webp", width: 1200, height: 1200 },
      { src: "/proto/img/real/stefan-scherrer/03-palaeo-vignetten.webp", width: 1200, height: 675 },
    ],
  },
  {
    id: "tara",
    name: "Tara",
    role: "Scientific Illustrator",
    description: "",
    bio: "",
    tags: [],
    openTo: [],
    portfolio: "",
    socialMedia: "",
    hasPhoto: false,
    images: [],
  },
  {
    id: "wong-chi-lui",
    name: "Wong Chi Lui",
    role: "Science Communicator",
    description: "",
    bio: "",
    tags: [],
    openTo: [],
    portfolio: "Wongchilui.com",
    socialMedia: "Instagram.com/little_lui_illustrations",
    hasPhoto: false,
    images: [
      { src: "/proto/img/real/wong-chi-lui/01-seidenbiene.webp", width: 1034, height: 1200 },
      { src: "/proto/img/real/wong-chi-lui/02-botanicals.webp", width: 1200, height: 661 },
      { src: "/proto/img/real/wong-chi-lui/03-buchdrucker-borkenkaefer.webp", width: 1034, height: 1200 },
    ],
  },
];

/** Members the current image-based card can render. */
export const PROTO_REAL_WITH_IMAGES = PROTO_REAL_MEMBERS.filter((m) => m.images.length > 0);

/** Members that need the typographic card variant (no artwork to show). */
export const PROTO_REAL_TEXT_ONLY = PROTO_REAL_MEMBERS.filter((m) => m.images.length === 0);

