import { writeFileSync } from 'node:fs';
import { backendDigestOnDisk } from './lib/backend-digest.mjs';
import { fileURLToPath } from 'node:url';
// The file set is backend-digest.mjs's, shared with the checkers that read it
// back from git (backend-current.mjs, verify-release.mjs); never select files here.
process.chdir(fileURLToPath(new URL('../', import.meta.url)));
const digest = backendDigestOnDisk('.');
writeFileSync('functions/src/releaseStamp.ts', `// Generated by scripts/stamp-backend.mjs. Do not edit.\nexport const backendLabels = { source_digest: '${digest}' };\n`);
console.log(`Backend source digest: ${digest}`);
