import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { BACKEND_FILES, backendDigest } from './lib/backend-digest.mjs';
import { fileURLToPath } from 'node:url';
process.chdir(fileURLToPath(new URL('../', import.meta.url)));
const files = {};
function scan(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = `${dir}/${entry.name}`;
    if (entry.isDirectory()) scan(path);
    else if (path.endsWith('.ts')) files[path] = readFileSync(path, 'utf8');
  }
}
scan('functions/src');
for (const path of BACKEND_FILES) files[path] = readFileSync(path, 'utf8');
const digest = backendDigest(files);
writeFileSync('functions/src/releaseStamp.ts', `// Generated by scripts/stamp-backend.mjs. Do not edit.\nexport const backendLabels = { source_digest: '${digest}' };\n`);
console.log(`Backend source digest: ${digest}`);
